-- Run this migration in the Supabase SQL editor before deploying the Vercel app.
CREATE SCHEMA IF NOT EXISTS coupons;

CREATE TABLE IF NOT EXISTS coupons.gc_coupons (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  url TEXT NOT NULL,
  code TEXT NOT NULL DEFAULT '',
  confidence TEXT NOT NULL DEFAULT '',
  source TEXT NOT NULL DEFAULT '',
  price TEXT NOT NULL DEFAULT '',
  location TEXT NOT NULL DEFAULT '',
  store_name TEXT NOT NULL DEFAULT '',
  address_line1 TEXT NOT NULL DEFAULT '',
  address_line2 TEXT NOT NULL DEFAULT '',
  city TEXT NOT NULL DEFAULT '',
  state TEXT NOT NULL DEFAULT '',
  expires DATE,
  error TEXT NOT NULL DEFAULT '',
  status TEXT NOT NULL DEFAULT 'fetched',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Existing installations predate the public ID required for on-demand code retrieval.
ALTER TABLE coupons.gc_coupons
  ADD COLUMN IF NOT EXISTS id BIGINT GENERATED BY DEFAULT AS IDENTITY;

UPDATE coupons.gc_coupons SET id = DEFAULT WHERE id IS NULL;

ALTER TABLE coupons.gc_coupons
  ALTER COLUMN id SET NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS gc_coupons_id_key
  ON coupons.gc_coupons (id);

-- Supports the crawler's idempotent URL/code/location write operation.
CREATE UNIQUE INDEX IF NOT EXISTS gc_coupons_url_code_location_key
  ON coupons.gc_coupons (url, code, location);

CREATE INDEX IF NOT EXISTS gc_coupons_public_offers_index
  ON coupons.gc_coupons (status, expires, state, city);
