-- Apply after 001_couponfinder.sql.
CREATE TABLE IF NOT EXISTS coupons.user_claims (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email TEXT NOT NULL,
  cid BIGINT NOT NULL REFERENCES coupons.gc_coupons(id),
  url TEXT NOT NULL,
  coupon_code TEXT,
  date_clicked TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS user_claims_cid_index
  ON coupons.user_claims (cid);

CREATE INDEX IF NOT EXISTS user_claims_date_clicked_index
  ON coupons.user_claims (date_clicked DESC);
